micronaut:
  application:
    name: API-MICRONAUT-V2
  server:
    port: 8880
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5433/db_micronout`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:admin}
    schema-generate: UPDATE
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
